# GET http://localhost:5000/
# content-type: application/json

# {
#     "name": "sample",
#     "email": "test@test.com",
#     "password": "123456"
# }

@ Does not work - Bearer Token
# GET http://localhost:5000/api/users/me
# Content-type: application/json
# Authorization: Bearer 

# {
#     "name": "sample",
#     "email": "test@test.com",
#     "password": "123456",
#     "token": "JWT-Token"
# }